name: cedmate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  provider: ^6.1.5+1
  path_provider: ^2.1.3
  flutter_localizations:
    sdk: flutter

  # Karten & Geodaten
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  http: ^1.2.2
  geolocator: ^10.1.0
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.0
  flutter_map_cancellable_tile_provider: ^3.1.1
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/mood_verybad.svg
    - assets/mood_bad.svg
    - assets/mood_meh.svg
    - assets/mood_good.svg
    - assets/mood_verygood.svg

  fonts:
    - family: Cedmate
      fonts:
        - asset: assets/fonts/Cedmate.ttf
